### ISSUE TITLE
Get Collection View returning none

### ISSUE THREAD

**Issue by rainerbird** [arturtamborski/notion-py#63]
I found this repository due to the original not being updated - but I found that get collection view method works on that one but not on this version.

Code:

```
from notion.client import NotionClient

# Obtain the `token_v2` value by inspecting your browser cookies on a logged-in (non-guest) session on Notion.so
client = NotionClient(token_v2=<token>)
cv = client.get_collection_view(<url>)
print(cv)
```

It logs "None" where as the original version logs "id=''"

Am I missing something? Docs are the same as the original

**Comment by arturtamborski** [comment]
Hi, thanks for creating this issue - this looks like a bug. I'll take a closer look at it.

**Comment by arturtamborski** [comment]
It was a bug and a quite interesting indeed. 
This [line](https://github.com/arturtamborski/notion-py/pull/67/files#diff-dfc6ac4d93094888b93848aadf48f8ab912b44baf71af92b5c7b3484f1bab6ddR246) was the main cause of errors. I mistakenly backported that line from original repo.
Other problem was [here](https://github.com/arturtamborski/notion-py/pull/67/files#diff-c9425a7773cc7457947d76d5217d10aaa3c5963c3b98a33f7bb82303d1d52947R433), the key for collection_id was not in `collection` but in `collection_id` of a particular `block`, so there had to be a two-way lookup.

Anyway, this should be now fixed on master branch, you can test it out for yourself and see if it works for you.
I'll do the release in a week or so after merging few more features/fixes.
