### ISSUE TITLE
record_id issue

### ISSUE THREAD

**Issue by agillies8** [arturtamborski/notion-py#71]
Just started getting this error this evening.
Package has been working well for me, but suddenly getting a new error when I'm creating the client object:

`client = NotionClient(token_v2=token)`

I am now getting this error:

`
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\....\env\lib\site-packages\notion\client.py", line 157, in __init__
    self._update_user_info()
  File "C:\....\env\lib\site-packages\notion\client.py", line 265, in _update_user_info
    data = self._store.store_record_map(data)
  File "C:....\env\lib\site-packages\notion\store.py", 
line 298, in store_record_map
    for record_id, record in records.items():
AttributeError: 'NoneType' object has no attribute 'items'
`

Checked to see if token has changed for some reason (it hasnt). Any ideas?

**Comment by ArtemErmulin** [comment]
Yeah, I have the same.

**Comment by arturtamborski** [comment]
Looks like a change in notion.so API, will see into it

**Comment by arturtamborski** [comment]
yup, they added new key `__json__` to `recordMap` (huge dict with state of basically everything). What's funny is that this key is empty, so I don't know why they did it. Anyway, it's simple enough to fix, will send patch shortly.

In the meantime you can fix by hand it like so:
```diff
diff --git a/notion/store.py b/notion/store.py
index 08aa37d..1de6a1a 100644
--- a/notion/store.py
+++ b/notion/store.py
@@ -294,6 +294,8 @@ class RecordStore:
 
     def store_record_map(self, data: dict) -> dict:
         data = data["recordMap"]
+        data.pop('__json__')
+
         for table, records in data.items():
             for record_id, record in records.items():
                 self._update_record(

```


Before:
```python
(Pdb) data['recordMap'].keys()
dict_keys(['notion_user', 'user_root', 'user_settings', 'space_view', 'space', 'block', 'collection'])
```

After:
```python
(Pdb) data['recordMap'].keys()
dict_keys(['notion_user', 'user_root', 'user_settings', 'space_view', 'space', 'block', 'collection', '__json__'])
```
